### ISSUE TITLE
'Best' model means best_loss or best_acc?

### ISSUE THREAD

**Issue by raymin0223** [Lee-Gihun/Pytorch-OSI-setup#26]
Until now, we define the best model as having the highest accuracy model.
Does it make sense that the lowest loss model is the best model?

**Comment by Lee-Gihun** [comment]
![acc](https://user-images.githubusercontent.com/20291737/67447481-fb915b00-f64e-11e9-858e-fcd3dc40ca33.png)
![loss](https://user-images.githubusercontent.com/20291737/67447483-fcc28800-f64e-11e9-8763-d1198405560b.png)

comparison between best_acc vs best_loss in ResNet18 with cifar-100 data.
best_acc performs much better. The reason is, the main target of our learning is accuracy, and we use loss because we cannot learn accuracy directly. If you can use accuracy directly like this situation, you should use accuracy, not loss. Now i close the issue.
